{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingchart.serviceAccountName" . }}
  labels:
{{ include "ingchart.labels" . | nindent 4 }}
{{- end -}}