
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"    
  hosts:
    - host: mychart.branch.io
      paths:
        - /path_bar
        - /path_foo

resources:
  limits:
    cpu: 400m
    memory: 496Mi
